server:
  port: 8088

bot:
  name: PodologiaLnrBot
  token: 6211665075:AAGKnnZFnxJvTCcw_4Blk2XiuZXVMiW075k

logging:
  level:
    org:
      springframework:
        web: debug
        jdbc: debug
    root: info
  file:
    path: './log'
    name: ${logging.file.path}/podologia.log
  logback:
    rollingpolicy:
      total-size-cap: 200MB